# .github/workflows/deploy-workflow.yml
name: Deploy Workflow

on:
  workflow_call:
    inputs:
      deployment:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input Variable 1
        run: |
          echo "Input: ${{ inputs.deployment }}"
          echo "Secret: ${{ secrets.LOCAL_SECRET }}" &&\
          echo "Variable: ${{ vars.LOCAL_VARIABLE }}"
